/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SignedMintingInterface extends ethers.utils.Interface {
  functions: {
    "asciiSender()": FunctionFragment;
    "generateSenderHash()": FunctionFragment;
    "recover(bytes)": FunctionFragment;
    "recoveredAddress(bytes)": FunctionFragment;
    "signer()": FunctionFragment;
    "toEthSignedMessageHash(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "asciiSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generateSenderHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "recover", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "recoveredAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "signer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "toEthSignedMessageHash",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "asciiSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateSenderHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recover", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoveredAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toEthSignedMessageHash",
    data: BytesLike
  ): Result;

  events: {};
}

export class SignedMinting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SignedMintingInterface;

  functions: {
    asciiSender(overrides?: CallOverrides): Promise<[string]>;

    generateSenderHash(overrides?: CallOverrides): Promise<[string]>;

    recover(signature: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    recoveredAddress(
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    signer(overrides?: CallOverrides): Promise<[string]>;

    toEthSignedMessageHash(
      s: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  asciiSender(overrides?: CallOverrides): Promise<string>;

  generateSenderHash(overrides?: CallOverrides): Promise<string>;

  recover(signature: BytesLike, overrides?: CallOverrides): Promise<string>;

  recoveredAddress(
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  toEthSignedMessageHash(s: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    asciiSender(overrides?: CallOverrides): Promise<string>;

    generateSenderHash(overrides?: CallOverrides): Promise<string>;

    recover(signature: BytesLike, overrides?: CallOverrides): Promise<string>;

    recoveredAddress(
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    signer(overrides?: CallOverrides): Promise<string>;

    toEthSignedMessageHash(
      s: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    asciiSender(overrides?: CallOverrides): Promise<BigNumber>;

    generateSenderHash(overrides?: CallOverrides): Promise<BigNumber>;

    recover(
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recoveredAddress(
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    signer(overrides?: CallOverrides): Promise<BigNumber>;

    toEthSignedMessageHash(
      s: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    asciiSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    generateSenderHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recover(
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recoveredAddress(
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    signer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    toEthSignedMessageHash(
      s: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
